### PR TITLE
Adding Euro summary statistics to APR Dashboard.

### PR DESCRIPTION
**Pull request by SamRozen**
Adding Euro statistics in Header section of the dashboard.

### CODE REVIEW

**Comment by SamRozen** [comment]
Fetching pending orders in staging doesn't seem to work (nor does it work locally for me). I'll try next week to test against reading prod db. I don't want to try this off regular hours.

**Comment by SamRozen** [comment]
I ran a local app with no rabbit mq client (only Apr.Repo and AprWeb.Endpoint in application.ex) and connected against the production database to verify that this change is working as expected and it does so I'm comfortable with moving forward and merging this (given that this shouldn't have any side effect on all the business critical applications).

**Comment by SamRozen** [comment]
Also from a stylistic perspective, I copy / pasted the code used for GBP. I'm guessing there must be a way to factor out all the common code reused for every currency but this is way past my comfort level in this repo.

**Comment by zephraph** [comment]
This looks good. I don't think we should worry too much about the stylistic parts at the moment. This view could use some love anyway. 

Let's send it out to staging!

**Pull request merged**
